name: Uwqaniksum
version: '${project.version}'
main: egoniks.uwqaniksum.Uwqaniksum
api-version: '1.20'

commands:
  giveweapon:
    description: Gives weapon to player.
#    usage: /<command> <name>
    aliases:
      - gw