name: Uwqaniksum
version: '${project.version}'
main: egoniks.uwqaniksum.Uwqaniksum
api-version: '1.20'

commands:
  giveweapon:
    description: Gives weapon to player.
    aliases:
      - gw

  spawnmob:
    description: Spawn mob near player.
    aliases:
      - sm